
# Sentence-related classes
# (used to print out a sentence)

VERB, NOUN, ADJECTIVE, ADVERBIAL, DIGIT, SENTENCE_AIM, PREPOSITION, SUBJECT, DIRECT_OBJECT, INDIRECT_OBJECT, RELATIVE, DETERMINER, QUANTIFIER, SENTENCE_TYPE = range(14)

