
# Sentence-related classes
# (used to print out a sentence)

VERB = "VERB"
TENSE = "TENSE"
NOUN = "NOUN"
ADJECTIVE = "ADJECTIVE"
ADJECTIVE_QUALIFIER = "ADJECTIVE_QUALIFIER" #like 'TOO expensive', 'VERY beautiful'...
ADVERBIAL = "ADVERBIAL"
VERBAL_ADVERBIAL = "VERBAL_ADVERBIAL"
DIGIT = "DIGIT"
SENTENCE_AIM = "SENTENCE_AIM"
PREPOSITION = "PREPOSITION"
CONJUNCTION = "CONJUNCTION"
DETERMINER = "DETERMINER"
QUANTIFIER = "QUANTIFIER"
SENTENCE_TYPE = "SENTENCE_TYPE"

# says if a verbal group is "affirmative" or "negative" (Verbal_Group.[affirmative|negative])
NEGATIVE = "NEGATIVE"
AFFIRMATIVE = "AFFIRMATIVE"

SUBJECT = "SUBJECT"
VERBAL_GROUP = "VERBAL_GROUP"
SECONDARY_VERBAL_GROUP = "SECONDARY_VERBAL_GROUP"
NOMINAL_GROUP = "NOMINAL_GROUP"
DIRECT_OBJECT = "DIRECT_OBJECT"
INDIRECT_OBJECT = "INDIRECT_OBJECT"
RELATIVE = "RELATIVE"
NOUN_CMPLT = "NOUN_CMPLT"
SENTENCE = "SENTENCE"
AGRAMMATICAL_SENTENCE = "AGRAMMATICAL_SENTENCE" # Sentence that could not be successfully parsed
SUB_SENTENCE = "SUB_SENTENCE"

RESOLVED = "RESOLVED"
NOT_RESOLVED = "NOT_RESOLVED"
ID = "ID" # ontology ID of a concept once resolved
